### ISSUE TITLE
Nepalbhasa fix image not showing for some dictionary words like hello

### ISSUE THREAD

**Issue by binamkayastha** [nepalcodes/nepalingo#143]
Primary: Devaki

I'm not sure why the error is happening. Try to figure out what's different with our dictionary search vs the one on nepalbhasa.org and fix ours.

We might need to modify the URL of the image to request a different width/height in the parameters

**Comment by SansCaar** [comment]
I think this error is due to the api of Nepal bhasa not providing the necessary image

**Comment by binamkayastha** [comment]
Taking ownership of this. I emailed nepalbhasa.org

**Comment by binamkayastha** [comment]
For now fixing the issue by using a non-square width/height until the API endpoint gets fixed
