### ISSUE TITLE
Create a logo for NepaLingo

### ISSUE THREAD

**Issue by binamkayastha** [nepalcodes/nepalingo#25]

**Comment by christikaes** [comment]
Make a logo that will be used on the loading page, app bar, and favicon
* Logo must work on both black and white backgrounds
* It must be an SVG file
* Exports to PNG, App Icon, etc also

![Image](https://github.com/nepalcodes/nepalingo/assets/1817295/bae38700-5613-4884-af96-b330090cd688)

![Image](https://github.com/nepalcodes/nepalingo/assets/1817295/1fe36c13-b3d0-425d-850c-9b35d46f9f4d)
