### ISSUE TITLE
Create a SQL Tables for user daily streaks and viewed flashcards

### ISSUE THREAD

**Issue by binamkayastha** [nepalcodes/nepalingo#28]
Outcome of the ticket:

- There are two tables created that are linked to the user via supabase user id
- Table1 includes data used for their daily streak
- Table2 includes data used to monitor which words they have learned, have not yet learned, or have not seen yet (Required for #32 )

You can use https://dbdiagram.io/home to design the table before creating it in supabase

**Comment by SansCaar** [comment]
A quick question, How do we want to add the viewed flashcards into the schema?

Can it be just an array of words? I think that is what you meant.
Also do we want to create a table based on the user feedback that some word is hard or not?

**Comment by binamkayastha** [comment]
Sorry I missed this message. What you did makes sense for now, we can always edit the tables for new features like word feedback and word difficulty
