### ISSUE TITLE
Create a word list component

### ISSUE THREAD

**Issue by christikaes** [nepalcodes/nepalingo#32]
Depends on #28 
* Make a component that takes in a list of word data and render each word line
* The words the user already learned are in Green, if they tried it before but got it wrong it's in red, if they haven't tried to learn it yet it's white

![Image](https://github.com/nepalcodes/nepalingo/assets/1817295/9a5afc53-e06c-477e-8b85-1837c12768b2)

**Comment by binamkayastha** [comment]
Decided not to do it because of the way the nepalbhasa.org backend API works (we currently have a random list of words and try until we find one that exists, so there is no comprehensive list of words to use)
