### ISSUE TITLE
Use Google Translate API to implement Maithili and backup for Newari

### ISSUE THREAD

**Issue by christikaes** [nepalcodes/nepalingo#35]
Primary: Nancy

* Implement into useDictionary for Maithili
* Update Newari to "fallback" to the translate API if the nepalbhasa endpoint fails

**Comment by christikaes** [comment]
Fill in this: https://github.com/nepalcodes/nepalingo/wiki/How-can-we-use-the-Google-Translate-Newari-API%3F

**Comment by binamkayastha** [comment]
No need to fill that out, just implement it
