### ISSUE TITLE
Create a function that makes an API request to nepalbhasa's backend when given a word. And hardcode a list of words into our frontend app

### ISSUE THREAD

**Issue by binamkayastha** [nepalcodes/nepalingo#42]

**Comment by christikaes** [comment]
Write this as a hook: https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

**Comment by christikaes** [comment]
Rough notes

type LanguageDictionary {
  language: "newari" | "tajpuriya"
   words: [string, string  ] // english, translated
}

useNewari(numberOfWords): LanguageDictionary {
// Gets data from NepalBhasa
{data}  = useQuery("nepalBhasa.com", {...})

return {
language: "newari",
words: //reformat data
}

}

useTajpuriya (number of words): LanguageDictionary {
{data} = //load from CSV

return {
language: "newari",
words: //reformat data
}

}
